const Ziggy = {"url":"http:\/\/localhost\/isd","port":null,"defaults":{},"routes":{"login":{"uri":"login","methods":["GET","HEAD"]},"logout":{"uri":"logout","methods":["POST"]},"register":{"uri":"register","methods":["GET","HEAD"]},"password.request":{"uri":"password\/reset","methods":["GET","HEAD"]},"password.email":{"uri":"password\/email","methods":["POST"]},"password.reset":{"uri":"password\/reset\/{token}","methods":["GET","HEAD"]},"password.update":{"uri":"password\/reset","methods":["POST"]},"password.confirm":{"uri":"password\/confirm","methods":["GET","HEAD"]},"auth.login":{"uri":"login-cust","methods":["POST"]},"home":{"uri":"home","methods":["GET","HEAD"]},"home.index":{"uri":"index","methods":["GET","HEAD"]},"boc.index":{"uri":"boc_processing","methods":["GET","HEAD"]},"pages.target_lodgement":{"uri":"target_lodgement","methods":["GET","HEAD"]},"incharge.index":{"uri":"settings\/incharge","methods":["GET","HEAD"]},"incharge.newuser":{"uri":"settings\/incharge\/newuser","methods":["POST"]},"settings.shippingline.index":{"uri":"settings\/shippingline","methods":["GET","HEAD"]},"settings.shippingline.put":{"uri":"settings\/shippingline","methods":["PUT"]},"user_incharge.update":{"uri":"user_incharge\/{user_incharge}","methods":["PUT","PATCH"]},"new_record.index":{"uri":"new_record","methods":["GET","HEAD"]},"new_record.create":{"uri":"new_record\/create","methods":["GET","HEAD"]},"new_record.store":{"uri":"new_record","methods":["POST"]},"new_record.show":{"uri":"new_record\/{new_record}","methods":["GET","HEAD"]},"new_record.edit":{"uri":"new_record\/{new_record}\/edit","methods":["GET","HEAD"]},"new_record.update":{"uri":"new_record\/{new_record}","methods":["PUT","PATCH"]},"new_record.destroy":{"uri":"new_record\/{new_record}","methods":["DELETE"]},"croweblists.index":{"uri":"cro_web_lists","methods":["GET","HEAD"]},"put.opnumber":{"uri":"opnumber","methods":["PUT"]}}};

if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    for (let name in window.Ziggy.routes) {
        Ziggy.routes[name] = window.Ziggy.routes[name];
    }
}

export { Ziggy };
